version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
      - match:
          update_type: "all"
          dependency_type: "all"