language: en_us
#supported language: zh_cn, en_us.

lore:
  bound: Tradeable
#supported bound type: Tradeable, Untradeable
#Tradeable: keep-item-on-death, personal trading is allowed.
#Untradeable: keep-item-on-death, cannot be stored, cannot be dropped.
  sendBoundingMessage: false
lifeskill:
  mining:
    - DIAMOND_ORE
    - EMERALD_ORE
    - EMERALD_ORE
    - GLOWING_REDSTONE_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - QUARTZ_ORE
    - REDSTONE_ORE
  chopping:
    - LOG
  fishing: 
    - CAUGHT_FISH
  killing:
    - MONSTER
  breeding:
    - ANIMALS
  smelting:
    - ITEM
#Stones ID: 0 = weapon stone, 1 = armor stone, 2 = concentrated weapon stone, 3 = concentrated armor stone
#In range of 0.01 means player will possibly get 1 out of 100 lifeskill event.
reward:
  mining:
    chance: 0.03
    drops:
      - 0
      - 1
      - 2
      - 3
  chopping:
    chance: 0.02
    drops:
      - 0
      - 1
      - 2
      - 3
  fishing:
    chance: 0.05
    drops:
      - 0
      - 1
  killing:
    chance: 0.01
    drops:
      - 0
      - 1
      - 2
      - 3
  breeding:
    chance: 0.08
    drops:
      - 0
      - 1
      - 2
      - 3
  smelting:
    chance: 0.01
    drops:
      - 0
      - 1
      - 2
      - 3

fireworkDelay: 0
fireworkCount: 1

FirstPhaseStarts: 7
SecondPhaseStarts: 15
DowngradePhaseStarts: 17
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
enhance:
  0:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+0"
    enchantments: []
  1:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+1"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  2:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+2"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:2
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:2
  3:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+3"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:3
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:3
  4:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+4"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:4
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:4
  5:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+5"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:5
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:5
  6:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+6"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:6
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:6
  7:
    baseChance: 20
    chanceIncreasePerFailstack: 2.5
    maximumFailstackApplied: 13
    failstackGainedPerFail: 1
    costToForceEnchant: 3
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+7"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:7
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:7
  8:
    baseChance: 17.5
    chanceIncreasePerFailstack: 2.0
    maximumFailstackApplied: 14
    failstackGainedPerFail: 1
    costToForceEnchant: 4
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+8"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:8
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:8
  9:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 15
    failstackGainedPerFail: 1
    costToForceEnchant: 5
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+9"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:9
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:9
  10:
    baseChance: 12.5
    chanceIncreasePerFailstack: 1.25
    maximumFailstackApplied: 16
    failstackGainedPerFail: 1
    costToForceEnchant: 7
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+10"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:10
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:10
  11:
    baseChance: 10
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 18
    failstackGainedPerFail: 1
    costToForceEnchant: 9
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+11"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:11
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:11
  12:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.63
    maximumFailstackApplied: 20
    failstackGainedPerFail: 1
    costToForceEnchant: 12
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+12"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:12
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:12
  13:
    baseChance: 5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 15
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+13"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:13
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:13
  14:
    baseChance: 2.5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 18
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+14"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:14
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:14
  15:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 2
    costToForceEnchant: 22
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+15"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:15
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:15
  16:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 35
    failstackGainedPerFail: 3
    costToForceEnchant: 27
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "PRI"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:16
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:16
  17:
    baseChance: 5.0
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 44
    failstackGainedPerFail: 4
    costToForceEnchant: 45
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "DUO"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:17
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:17
  18:
    baseChance: 2.0
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 90
    failstackGainedPerFail: 5
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TRI"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:18
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:18
  19:
    baseChance: 1.5
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 124
    failstackGainedPerFail: 6
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TET"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:19
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:19
  20:
    baseChance: -1
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: false
    fireworkRounds: -1
    name: "PEN"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:20
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:20
grade:
  0:
    name: "Crimson Flame"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  1:
    name: "Destruction"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  2:
    name: "Temptation"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  3:
    name: "Ultimate"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  4:
    name: "Kzarka"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  5:
    name: "Dandelion"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1

        