language: en_us
#supported language: zh_cn, en_us.

lore:
  bound: tradeable
#supported bound type: tradeable, untradeable
#Tradeable: keep-item-on-death, personal trading is allowed.
#Untradeable: keep-item-on-death, cannot be stored, cannot be dropped.
  sendBoundingMessage: false
lifeskill:
  mining:
    - DIAMOND_ORE
    - EMERALD_ORE
    - EMERALD_ORE
    - GLOWING_REDSTONE_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - QUARTZ_ORE
    - REDSTONE_ORE
  chopping:
    - LOG
  fishing: 
    - CAUGHT_FISH
  killing:
    - MONSTER
  breeding:
    - ANIMALS
  smelting:
    - ITEM
#Stones ID: 0 = weapon stone, 1 = armor stone, 2 = concentrated weapon stone, 3 = concentrated armor stone
#In range of 0.01 means player will possibly get 1 out of 100 lifeskill event.
reward:
  mining:
    chance: 0.03
    drops:
      - 0
      - 1
      - 2
      - 3
  chopping:
    chance: 0.02
    drops:
      - 0
      - 1
      - 2
      - 3
  fishing:
    chance: 0.05
    drops:
      - 0
      - 1
  killing:
    chance: 0.01
    drops:
      - 0
      - 1
      - 2
      - 3
  breeding:
    chance: 0.08
    drops:
      - 0
      - 1
      - 2
      - 3
  smelting:
    chance: 0.01
    drops:
      - 0
      - 1
      - 2
      - 3

fireworkDelay: 0
fireworkCount: 1

material:
  stoneTypes:
    #0
    - GHAST_TEAR
    #1
    - GOLD_NUGGET
    #2
    - SUGAR
    #3
    - GLOWSTONE_DUST
  armor:
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
    - GOLD_HELMET
    - GOLD_CHESTPLATE
    - GOLD_LEGGINGS
    - GOLD_BOOTS
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
  weapon:
    - DIAMOND_SWORD
    - GOLD_SWORD
    - STONE_SWORD
    - WOOD_SWORD
    - DIAMOND_AXE
    - GOLD_AXE
    - STONE_AXE
    - WOOD_AXE
    - IRON_SWORD
    - IRON_AXE
    - WOOD_AXE
    

FirstPhaseStarts: 7
SecondPhaseStarts: 15
DowngradePhaseStarts: 17
#https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
enhance:
  0:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+0"
    enchantments: []
  1:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+1"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:1
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:1
  2:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+2"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:2
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:2
  3:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+3"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:3
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:3
  4:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+4"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:4
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:4
  5:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+5"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:5
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:5
  6:
    baseChance: 100
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+6"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:6
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:6
  7:
    baseChance: 20
    chanceIncreasePerFailstack: 2.5
    maximumFailstackApplied: 13
    failstackGainedPerFail: 1
    costToForceEnchant: 3
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+7"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:7
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:7
  8:
    baseChance: 17.5
    chanceIncreasePerFailstack: 2.0
    maximumFailstackApplied: 14
    failstackGainedPerFail: 1
    costToForceEnchant: 4
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+8"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:8
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:8
  9:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 15
    failstackGainedPerFail: 1
    costToForceEnchant: 5
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+9"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:9
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:9
  10:
    baseChance: 12.5
    chanceIncreasePerFailstack: 1.25
    maximumFailstackApplied: 16
    failstackGainedPerFail: 1
    costToForceEnchant: 7
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+10"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:10
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:10
  11:
    baseChance: 10
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 18
    failstackGainedPerFail: 1
    costToForceEnchant: 9
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+11"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:11
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:11
  12:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.63
    maximumFailstackApplied: 20
    failstackGainedPerFail: 1
    costToForceEnchant: 12
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+12"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:12
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:12
  13:
    baseChance: 5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 15
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+13"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:13
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:13
  14:
    baseChance: 2.5
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 1
    costToForceEnchant: 18
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+14"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:14
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:14
  15:
    baseChance: 15
    chanceIncreasePerFailstack: 1.5
    maximumFailstackApplied: 25
    failstackGainedPerFail: 2
    costToForceEnchant: 22
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "+15"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:15
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:15
  16:
    baseChance: 7.5
    chanceIncreasePerFailstack: 0.75
    maximumFailstackApplied: 35
    failstackGainedPerFail: 3
    costToForceEnchant: 27
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "PRI"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:17
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:17
  17:
    baseChance: 5.0
    chanceIncreasePerFailstack: 0.5
    maximumFailstackApplied: 44
    failstackGainedPerFail: 4
    costToForceEnchant: 45
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "DUO"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:19
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:19
  18:
    baseChance: 2.0
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 90
    failstackGainedPerFail: 5
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TRI"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:21
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:21
  19:
    baseChance: 1.5
    chanceIncreasePerFailstack: 0.25
    maximumFailstackApplied: 124
    failstackGainedPerFail: 6
    costToForceEnchant: -1
    fireworkIfSuccessful: true
    fireworkRounds: 1
    name: "TET"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:23
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:23
  20:
    baseChance: -1
    chanceIncreasePerFailstack: -1
    maximumFailstackApplied: -1
    failstackGainedPerFail: -1
    costToForceEnchant: -1
    fireworkIfSuccessful: false
    fireworkRounds: -1
    name: "PEN"
    enchantments:
      WEAPON:
        - DAMAGE_ALL:25
      ARMOR:
        - PROTECTION_ENVIRONMENTAL:25
weaponGrade:
  0:
    name: ""
    enchantments: []
  1:
    name: "Crimson Flame"
    enchantments:
        - FIRE_ASPECT:1
  2:
    name: "Destruction"
    enchantments:
        - DAMAGE_ALL:1
  3:
    name: "Temptation"
    enchantments:
        - LOOT_BONUS_MOBS:1
  4:
    name: "Ultimate"
    enchantments:
        - DAMAGE_ALL:2
        - DURABILITY:2
  5:
    name: "Kzarka"
    enchantments:
        - DAMAGE_ALL:3
        - DURABILITY:3
  6:
    name: "Dandelion"
    enchantments:
        - DAMAGE_ARTHROPODS:3
        - DAMAGE_UNDEAD:3
        - DURABILITY:3
        - LOOT_BONUS_MOBS:3
armorGrade:
  0:
    name: ""
    enchantments: []
  1:
    name: "Agility"
    enchantments:
        - PROTECTION_FALL:1
  2:
    name: "Intimidation"
    enchantments:
        - THORNS:1
  3:
    name: "Iron Wall"
    enchantments:
        - PROTECTION_EXPLOSIONS:1
  4:
    name: "Ultimate"
    enchantments:
        - PROTECTION_ENVIRONMENTAL:2
        - DURABILITY:2
name:
  axe: "Ain Axe"
  sword: "Great Sword"
  bow: "Long Bow"
pickaxe:
  0:
    name: "Broken Pickaxe"
    enchantments: []
  1:
    name: "Improved Pickaxe"
    enchantments:
      - DURABILITY:1
  2:
    name: "Sharp Pickaxe"
    enchantments:
      - DIG_SPEED:1
  3:
    name: "Steel Pickaxe"
    enchantments:
      - DIG_SPEED:1
      - DURABILITY:1
  4:
    name: "Lucky Steel Pickaxe"
    enchantments:
      - DIG_SPEED:3
      - DURABILITY:3
      - LOOT_BONUS_BLOCKS:1
  5:
    name: "Magic Pickaxe"
    enchantments:
      - DIG_SPEED:4
      - DURABILITY:4
  6:
    name: "Lucky Magic Pickaxe"
    enchantments:
      - DIG_SPEED:5
      - DURABILITY:5
      - LOOT_BONUS_BLOCKS:2
  7:
    name: "Master Pickaxe"
    enchantments:
      - DIG_SPEED:6
      - DURABILITY:6
  8:
    name: "Lucky Master Pickaxe"
    enchantments:
      - DIG_SPEED:7
      - DURABILITY:7
      - LOOT_BONUS_BLOCKS:3
  9:
    name: "Lucky Shining Magic Pickaxe"
    enchantments:
      - DIG_SPEED:8
      - DURABILITY:8
      - LOOT_BONUS_BLOCKS:4
  10:
    name: "Lucky Shining Master Pickaxe"
    enchantments:
      - DIG_SPEED:10
      - DURABILITY:10
      - LOOT_BONUS_BLOCKS:5
fishing rod:
  0:
    name: "Broken Fishing Rod"
    enchantments: []
  1:
    name: "Fishing Rod"
    enchantments:
      - DURABILITY:1
  2:
    name: "Old Fishing Rod"
    enchantments:
      - LUCK:1
  3:
    name: "Thick Fishing Rod"
    enchantments:
      - LUCK:1
      - DURABILITY:1
  4:
    name: "Steel Fishing Rod"
    enchantments:
      - LUCK:3
      - LURE:3
      - DURABILITY:3
  5:
    name: "Triple-Float Rod"
    enchantments:
      - LUCK:3
      - LURE:3
      - DURABILITY:4
  6:
    name: "Lucky Silver Fishing Rod"
    enchantments:
      - LUCK:3
      - LURE:4
      - DURABILITY:4
  7:
    name: "Lucky Golden Fishing Rod"
    enchantments:
      - LUCK:4
      - LURE:4
      - DURABILITY:4
  8:
    name: "Splendid Golden Fishing Rod"
    enchantments:
      - LUCK:4
      - LURE:4
      - DURABILITY:5
  9:
    name: "Fancy Golden Fishing Rod"
    enchantments:
      - LUCK:4
      - LURE:4
      - DURABILITY:5
  10:
    name: "Artisan Fishing Rod"
    enchantments:
      - LUCK:5
      - LURE:5
      - DURABILITY:5
        